name: skill_testing_platform
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  google_sign_in: ^6.2.1
  flutter_animate: ^4.0.0
  google_fonts: ^6.2.1
  http: ^1.2.2
  flutter_markdown: ^0.7.3
  uuid: ^4.5.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png

dependency_overrides:
  firebase_core_web: ^2.18.0
  firebase_auth_web: ^5.13.1
  cloud_firestore_web: ^4.2.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 23 # Optional: Set minimum Android SDK