// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJT8tEwAbXCVPTQBJc_f5fEpZ_xcguLb0',
    appId: '1:225743670427:web:dd1dac92983b6b7696ca3e',
    messagingSenderId: '225743670427',
    projectId: 'feedbackai-5c0b7',
    authDomain: 'feedbackai-5c0b7.firebaseapp.com',
    storageBucket: 'feedbackai-5c0b7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFoqd7QJ-wmzFti6bDsGjrIAK1VP84vNw',
    appId: '1:225743670427:android:470266c2d0b6127f96ca3e',
    messagingSenderId: '225743670427',
    projectId: 'feedbackai-5c0b7',
    storageBucket: 'feedbackai-5c0b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB55l6yT11BU1N98EyLsBwfvF6UrveRvz8',
    appId: '1:225743670427:ios:15ee3655fa5b2ebf96ca3e',
    messagingSenderId: '225743670427',
    projectId: 'feedbackai-5c0b7',
    storageBucket: 'feedbackai-5c0b7.firebasestorage.app',
    iosClientId: '225743670427-5cu84n7khrsg6cshptfal8uk9194ar1a.apps.googleusercontent.com',
    iosBundleId: 'com.example.skillTestingPlatform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB55l6yT11BU1N98EyLsBwfvF6UrveRvz8',
    appId: '1:225743670427:ios:15ee3655fa5b2ebf96ca3e',
    messagingSenderId: '225743670427',
    projectId: 'feedbackai-5c0b7',
    storageBucket: 'feedbackai-5c0b7.firebasestorage.app',
    iosClientId: '225743670427-5cu84n7khrsg6cshptfal8uk9194ar1a.apps.googleusercontent.com',
    iosBundleId: 'com.example.skillTestingPlatform',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJT8tEwAbXCVPTQBJc_f5fEpZ_xcguLb0',
    appId: '1:225743670427:web:52f77574e5c48cd396ca3e',
    messagingSenderId: '225743670427',
    projectId: 'feedbackai-5c0b7',
    authDomain: 'feedbackai-5c0b7.firebaseapp.com',
    storageBucket: 'feedbackai-5c0b7.firebasestorage.app',
  );
}
